RC/rccoin/wallet/account/urls.py
from django.urls import path
from . import views

app_name = 'account'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('forget_id/', views.forget_id, name='forget_id'),
    path('forget_pwd/', views.forget_pwd, name='forget_pwd'),
    path('agreement/', views.agreement, name='agreement'),
    path('chk_username/', views.chk_username),
    path('chk_password/', views.chk_password),
    path('signup/', views.signup, name='signup'),
    path('info/', views.get_myinfo, name='info'),
    path('<str:op>/identity/', views.identity, name='identity'),
    path('<str:op>/identity/<int:s_id>/', views.identity, name='identity2'),
    path('edit/', views.account_edit, name='edit'),
    path('chg_pwd/', views.change_pwd, name='chg_pwd'),
]

RC/rccoin/wallet/info/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import NoticeLV

app_name = 'info'

urlpatterns = [
    path('list/', NoticeLV.as_view(), name='list'),
    # path('notice/add/', views.add, name='add'),
    # path('notice/read/<int:n_id>', views.read, name='read'),
    # path('notice/modify/<int:n_id>', views.add, name='modify'),
    # path('notice/delete/<int:n_id>', views.delete, name='delete'),
]

RC/rccoin/wallet/rccoin/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import handler400, handler403, handler404, handler500
from . import views
handler400 = 'rccoin.views.error_400'
handler403 = 'rccoin.views.error_403'
handler404 = 'rccoin.views.error_404'
handler500 = 'rccoin.views.error_500'

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('accounts/', include('django.contrib.auth.urls')),

    path('', views.index, name='index'),
    path('<str:op>/done/', views.done, name='done'),
    
    path('intro/', views.intro, name='intro'),
    path('guide/', views.guide, name='guide'),
    path('map/', views.map, name='map'),

    path('operate/', include('operate.urls', namespace='operate')),
    path('account/', include('account.urls', namespace='account')),
    path('store/', include('store.urls', namespace='store')),
    path('wallet/', include('wallet.urls', namespace='wallet')),
    path('info/', include('info.urls', namespace='info')),
    path('board/', include('board.urls', namespace='board')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

RC/rccoin/wallet/store/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from .views import *

app_name = 'store'

urlpatterns = [
    path('apply/', edit_store, name='apply'),
    path('info/', get_myStore, name='info'),
    path('edit/', edit_store, name='edit'),
    path('<int:s_id>/delete/', del_store, name='delete'),
    path('qrcode/', get_qrcode, name='qrcode'),
    path('list/', StorePV.as_view(), name='store_list'),
    path('list/filter/<int:loc>/', filteredStoresPV.as_view(), name='filteredStores'),
    path('list/detail/<int:store_id>/', detailView, name='filteredStoresDetail')

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

RC/rccoin/wallet/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'wallet'

urlpatterns = [
    path('info/', views.read_wallet, name="info"),
    path('publish/', views.publish, name="publish"),
    path('remittance/', views.remittance, name="remittance"),
    path('payment/', views.payment, name="payment"),
    path('history/', views.get_history),
    path('receipt/', views.get_receipt),
    path('cancel/', views.cancel, name="cancel"),
    path('cancel_payment/', views.cancel_payment, name="cancel_payment"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

RC/rccoin/wallet/templates/base.html
<!DOCTYPE html>
<html lang="ko">
  
  <head>
    
    {% block head %}
    {% load staticfiles %}
    {% endblock head %}

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>{% block title%}울릉도 지역화폐 RC coin{% endblock title %}</title>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'bootstrap-4.2.1-dist/css/bootstrap.css' %}">
    <!-- Loading spinner CSS -->
    <link rel="stylesheet" href="{% static 'spinner/css/jquery.loadingModal.css' %}">
    <!-- Style CSS -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    
    <!-- Favicon -->
    <link rel="shortcut icon" href="{% static 'img/favicon.ico' %}" type="image/x-icon" />
    <link rel="icon" href="{% static 'img/favicon.ico' %}" type="image/x-icon" />
    
    <style>
        {% block css %} 
        {% endblock css %}
    </style>

</head>

<body>

    <!-- Navigation-->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top shadow">
        <div class="container">
         
            <a class="navbar-brand" href="{% url 'index' %}">
                <img src="{% static 'img/logo.png' %}">
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
         
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
                <ul class="navbar-nav">
                    <div class="dropdown-divider"></div>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="intro" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            소개
                        </a>
                        <div class="dropdown-menu" aria-labelledby="intro">
                            <a class="dropdown-item" href="{% url 'intro' %}">RC코인이란?</a>
                            <a class="dropdown-item" href="{% url 'guide' %}">이용안내</a>
                        </div>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'map' %}">오시는 길<span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="info" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            정보마당
                        </a>
                        <div class="dropdown-menu" aria-labelledby="info">
                            <a class="dropdown-item" href="{% url 'info:list' %}">공지사항</a>
                        </div>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="community" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            커뮤니티
                        </a>
                        <div class="dropdown-menu" aria-labelledby="community">
                            <a class="btn_board_type_1 dropdown-item" onclick="back_to_list(1)" href="{% url 'board:list' %}">가맹게시판</a>
                            <input type="hidden" id="board_type_1" value="1">
                            <a class="btn_board_type_2 dropdown-item" onclick="back_to_list(2)" href="{% url 'board:list' %}">회원게시판</a>
                            <input type="hidden" id="board_type_2" value="2">
                        </div>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'store:store_list' %}?page=1">가맹점</a>
                    </li>
                    <li class="nav-link d-none d-lg-block">|</li>
                    <div class="dropdown-divider"></div>
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account:logout' %}">로그아웃</a>
                    </il>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="mypage" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            마이페이지
                        </a>
                        <div class="dropdown-menu" aria-labelledby="mypage">
                            <a class="dropdown-item" href="{% url 'account:info' %}">계정관리</a>
                            <a class="dropdown-item" href="{% url 'wallet:info' %}">계좌관리</a>
                            {% if user.profile.type == 1 %}
                            <a class="dropdown-item" href="{% url 'store:info' %}">가맹점관리</a>
                            {% elif user.profile.type == 2 %}
                            <a class="dropdown-item" href="{% url 'store:apply' %}">가맹점신청</a>
                            {% endif %}
                            <a class="dropdown-item" href="{% url 'wallet:publish' %}">자전거타기</a>
                        </div>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account:login' %}">로그인</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account:agreement' %}">회원가입</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        
        </div>
    </nav>

    <!-- Contents -->
    <br><br>
    {% block body %} {% endblock body %}
    
    <!-- Footer -->
    <div class="card text-center">
        <div class="bg-dark">
            <div class="container">
                <div class="row" style="text-align: left; margin: 3% 0;">
                    <div class="col-md-4">
                        <h5 class="card-title"><a href="{% url 'index' %}"><strong>RC coin</strong></a></h5>
                        <p class="card-text">
                            RC코인은 울릉도의 지역경제를 활성화시키기 위하여 만들어진 친환경 코인입니다. 자전거를 타는 활동을 통하여 RC코인을 분배받을 수 있습니다. 
                        </p><br class="d-block d-md-none">
                    </div>
                    <div class="col-md-2">
                        <div class="card-title">
                            <h5><strong>소개</strong></h5>
                            <ul class="card-text">
                                <li><a href="{% url 'intro' %}">RC코인이란?</a></li>
                                <li><a href="{% url 'guide' %}">이용안내</a></li>
                            </ul>
                            <br class="d-block d-md-none">
                        </div>
                    </div>
                    <div class="col-md-2">
                        <div class="card-title">
                            <h5><strong>정보마당</strong></h5>
                            <ul class="card-text">
                                <li><a href="{% url 'info:list' %}">공지사항</a></li>
                            </ul>
                            <br class="d-block d-md-none">
                        </div>
                    </div>
                    <div class="col-md-2">
                        <div class="card-title">
                            <h5><strong>커뮤니티</strong></h5>
                            <ul class="card-text">
                                <li>
                                    <a onclick="back_to_list(1)" href="{% url 'board:list' %}">가맹게시판</a>
                                    <input type="hidden" id="board_type_1" value="1">
                                </li>
                                <li>
                                    <a onclick="back_to_list(2)" href="{% url 'board:list' %}">가맹게시판</a>
                                    <input type="hidden" id="board_type_2" value="2">
                                </li>
                            </ul>
                            <br class="d-block d-md-none">
                        </div>
                    </div>
                    <div class="col-md-2">
                        <div class="card-title">
                            <h5><strong>가맹점</strong></h5>
                            <ul class="card-text">
                                <li><a href="{% url 'store:filteredStores' 3 %}?page=1">북면</a></li>
                                <li><a href="{% url 'store:filteredStores' 2 %}?page=1">서면</a></li>
                                <li><a href="{% url 'store:filteredStores' 1 %}?page=1">울릉읍</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>    
        <div class="card-footer text-muted bg-light">
            <div class="container">
                <p>© Copyrights Team RGB. All rights reserved.</p>
            </div>
        </div>
    
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'bootstrap-4.2.1-dist/js/bootstrap.js' %}"></script>
    <!-- Loading spinner JS -->
    <script src="{% static 'spinner/js/jquery.loadingModal.js' %}" type="text/javascript"></script>
    {% block js %} {% endblock js %}
  
  </body>
</html>

RC/rccoin/wallet/templates/done.html
{% extends 'base.html' %}

{% block head %}
{% load staticfiles %}
{% endblock head %}

{% block css %}
.w-380 {
    width: 380px;
}
@media (max-width: 560px) {
    .form-group {
        padding-left: 10px;
        padding-right: 10px;
    }
}
@media (max-width: 380px) {
    .w-380 {
        width: 100%;
    }
}
{% endblock css %}

{% block body %}


    <!-- Title -->
    <div id="contents" class="page-header">
        <div class="container">
            <div class="row page-title">
                <a>{{ msg.title }}</a>
            </div>
        </div>
    </div>
    
    <div id="contents">
        <div class="container">
            <div class="row justify-content-center page">
                <div class="row w-380">
                    
                    <div class="col card">
                        <div class="card-body">

                            <!-- Message -->
                            <div class="profile-sidebar">
                                <div class="profile-usertitle">
                                    <div class="text-center">
                                        <img src="{% static 'img/mascot.jpg' %}" />
                                    </div>
                                    
                                    <div class="profile-usertitle-name text-center">
                                        {{ msg.msg }}
                                    </div>
                                    {% if msg.submsg %}
                                    <div class="profile-usertitle-job text-center" style="margin-bottom: 30px;">
                                        {{ msg.submsg }}
                                    </div>
                                    {% endif %}
                                </div>
                                
                                <div class="form-group m-0">
                                    <a href="{% url msg.url %}" class="btn btn-success btn-block">확인</a>
                                </div>
                                
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
        

{% endblock body %}

{% block js %}
{% endblock js %}

RC/rccoin/wallet/templates/error.html
<!DOCTYPE html>
<html lang="ko">
  
  <head>
    {% load staticfiles %}

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>울릉도 지역화폐 RC coin</title>

    <!-- Favicon -->
    <link rel="shortcut icon" href="{% static 'img/favicon.ico' %}" type="image/x-icon" />
    <link rel="icon" href="{% static 'img/favicon.ico' %}" type="image/x-icon" />

    <style>
        body {
            display: inline-block;
            background: #00AFF9 url(https://cbwconline.com/IMG/Codepen/Unplugged.png) center/cover no-repeat;
            height: 100vh;
            margin: 0;
            color: white;
        }
        h1 {
            margin: .8em 3rem;
            font: 4em Roboto;
        }
        p {
            display: inline-block;
            margin: .2em 3rem;
            font: 2em Roboto;
        }
    </style>
</head>

<body>
    <h1>Error {{ code }}</h1>
    <p>{{ title }}<br>
    {{ msg }}</p>
</body>

</html>

RC/rccoin/wallet/templates/index.html
{% extends 'base.html' %}

{% block head %}
{% load staticfiles %}
{% endblock head %}

{% block css %}
    #video {
        position: relative;
        overflow: hidden;
        height: 68vh;
        min-height: 35rem;
        width: 100%;
    }
    #video .overlay {
        position: absolute;
        top: 0;
        left: 0;
        height: 86%;
        width: 100%;
        opacity: 0.5;
        z-index: 0;
    }
    #video .A {
        position: absolute;
        top: 50%;
        left: 50%;
        min-width: 100%;
        min-height: 100%;
        width: auto;
        height: auto;
        z-index: 1;
        -ms-transform: translateX(-50%) translateY(-50%);
        -moz-transform: translateX(-50%) translateY(-50%);
        -webkit-transform: translateX(-50%) translateY(-50%);
        transform: translateX(-50%) translateY(-50%);
    }
    

    @media (pointer: coarse) and (hover: none) {
        #video {
            background: url("{% static '/img/대문.png'%}") black no-repeat center center scroll;
            background-size: cover;
        }
        #video .A {
            display: none;
        }
    }

{% endblock css %}

{% block body %}

    <!-- Intro movie -->
    <section id="video">
        <div class="overlay"></div>
        <video class="A" playsinline="playsinline" autoplay="autoplay" muted="muted" loop="loop">
            <source src="{% static 'video/movieopti.mp4'%}" type="video/mp4">
        </video>
    </section>
  
{% endblock body %}

{% block js %}
{% endblock js %}

RC/rccoin/wallet/templates/intro.html
{% extends 'base.html' %}

{% block head %}
{% load staticfiles %}
{% endblock head %}

{% block css %}
.bg-overlay {
    background: linear-gradient(rgba(0,0,0,.7), rgba(0,0,0,.7)), url("{% static 'img/ug.jpg' %}");
    background-repeat: no-repeat;
    background-size: cover;
    background-position: center center;
    color: #fff;
    height: 450px;
}
.text-head {
    font-size: 1.5rem;
    font-weight: 600;
    padding-left: 20px;
    padding-right: 20px;
}
.text-text {
    font-size: 1.2rem;
    font-weight: 500;
    padding-left: 20px;
    padding-right: 20px;
}
.text-point {
    font-size: 1.3rem;
    font-weight: 600;
    padding-left: 20px;
    padding-right: 20px;
}
strong.text-green {
    color: #00c746;
}

@media(max-width: 767px) {
    .text-head {
        font-size: 1.2rem;
    }
    .text-text {
        font-size: 1rem;
    }
    .text-point {
        font-size: 1.2rem;
    }
}
{% endblock css %}
{% block body %}


    <!-- Title -->
    <div id="contents" class="page-header">
        <div class="container">
            <div class="row page-title">
                <a>소개</a>
            </div>
        </div>
    </div>
    
    <!-- Filter button -->
    <div id="contents">
        <div class="container">
            
            <div class="row justify-content-center page">
                <div class="col-md card">
                    <div class="card-body">
                        <!-- Subtitle -->
                        <h5 class="card-subtitle"><a style="color:#00c746;">|</a> RC코인이란?</h5>
                    </div>
                </div>
            </div>

            <div class="row justify-content-center page">
                <div class="col-md card">
                    <div class="card-body">
                        <!-- Intro -->
                        <div class="row bg-overlay justify-content-center align-items-center page">
                            <div class="text-center">
                                <div class="text-head">
                                    "<strong class="text-green">RC</strong>란 지역화폐를 뜻하는 <strong class="text-green">REGION CURRENCY</strong>의 약자로<br>
                                    지역공동체를 실현하는 지역화폐 기본 통화 단위입니다."
                                </div>
                                <div class="text-text">
                                    <br>
                                    <strong class="text-point text-green">1RC = 1원</strong><br>
                                    <br>
                                    사회적 가치 - 자전거 트래킹<br>
                                    울릉지역화폐 - 사회적 가치 실현을 통한 지역화폐의 적립<br>
                                    가맹점 - 음식점, 레저스포츠 시설, 숙박시설
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>

{% endblock body %}

{% block js %}
{% endblock js %}

RC/rccoin/wallet/templates/map.html
{% extends 'base.html' %}

{% block head %}
{% load staticfiles %}
{% endblock head %}

{% block css %}
.card-title {
    color: #212529;
    margin-top: 10px;
    margin-bottom: 10px;
    font-weight: 600;
}
.card-sub {
    color: #212529;
    font-weight: 400;
    float: left;
    margin-top: 5px;
    margin-left: 10px;
    margin-right: 10px;
}
.card-link {
    color: #212529;
    font-weight: 400;
    float: right;
    margin-top: 5px;
    margin-left: 10px;
    margin-right: 10px;
    margin-bottom: 10px;
}
.box {
    border: 1px solid #0000001a;
    border-radius: 5px;
}
{% endblock css %}
{% block body %}


    <!-- Title -->
    <div id="contents" class="page-header">
        <div class="container">
            <div class="row page-title">
                <a>오시는 길</a>
            </div>
        </div>
    </div>
    
    <!-- Filter button -->
    <div id="contents">
        <div class="container">
            
            <div class="row justify-content-center page">
                <div class="col-md card">
                    <div class="card-body">
                        <!-- Subtitle -->
                        <h5 class="card-subtitle"><a style="color:#00c746;">|</a> 당신을 울릉도로 안내합니다</h5>
                    </div>
                </div>
            </div>

            <div class="row justify-content-center page">
                <div class="col-md card">
                    <div class="card-body">
                        
                        <!-- Map guide -->
                        <div class="row">
                            <div class="col-lg-4 col-md-6 col-sm-12 card text-center" style="margin-bottom: 10px;">
                                <a href="http://www.ulleung.go.kr/tour/page.htm?mnu_uid=2052&" target="_blank" class="box">
                                <img class="card-img-top" src="{% static 'img/map/포항.gif' %}" alt="포항에서 오시는 길">
                                <div class="card-body" id="card">
                                    <div class="card-title">포항에서 오시는 길</div>
                                    <div class="card-sub">포항 여객터미널</div>
                                    <div class="card-link">상세보기</div>
                                </div>
                                </a>
                            </div>
                            
                            <div class="col-lg-4 col-md-6 col-sm-12 card text-center" style="margin-bottom: 10px;">
                                <a href="http://www.ulleung.go.kr/tour/page.htm?mnu_uid=2053&" target="_blank" class="box">
                                <img class="card-img-top" src="{% static 'img/map/후포.gif' %}" alt="후포에서 오시는 길">
                                <div class="card-body" id="card">
                                    <div class="card-title">후포에서 오시는 길</div>
                                    <div class="card-sub">후포항 여객터미널</div>
                                    <div class="card-link">상세보기</div>
                                </div>
                                </a>
                            </div>

                            <div class="col-lg-4 col-md-6 col-sm-12 card text-center" style="margin-bottom: 10px;">
                                <a href="http://www.ulleung.go.kr/tour/page.htm?mnu_uid=2054&" target="_blank" class="box">
                                <img class="card-img-top" src="{% static 'img/map/목포.gif' %}" alt="묵호에서 오시는 길">
                                <div class="card-body" id="card">
                                    <div class="card-title">묵호에서 오시는 길</div>
                                    <div class="card-sub">묵포 여객터미널</div>
                                    <div class="card-link">상세보기</div>
                                </div>
                                </a>
                            </div>
                            
                            
                            <div class="col-lg-4 col-md-6 col-sm-12 card text-center" style="margin-bottom: 10px;">
                                <a href="http://www.ulleung.go.kr/tour/page.htm?mnu_uid=2055&" target="_blank" class="box">
                                <img class="card-img-top" src="{% static 'img/map/강릉.gif' %}" alt="강릉에서 오시는 길">
                                <div class="card-body" id="card">
                                    <div class="card-title">강릉에서 오시는 길</div>
                                    <div class="card-sub">강릉(안목)항 여객터미널</div>
                                    <div class="card-link">상세보기</div>
                                </div>
                                </a>
                            </div>
                            
                            <div class="col-lg-4 col-md-6 col-sm-12 card text-center" style="margin-bottom: 10px;">
                                <a href="http://www.ulleung.go.kr/tour/page.htm?mnu_uid=2067&" target="_blank" class="box">
                                <img class="card-img-top" src="{% static 'img/map/독도.gif' %}" alt="독도 가는 길">
                                <div class="card-body" id="card">
                                    <div class="card-title">독도 가는 길</div>
                                    <div class="card-sub">여객선 이용시 유의사항</div>
                                    <div class="card-link">상세보기</div>
                                </div>
                                </a>
                            </div>

                            <div class="col-lg-4 col-md-6 col-sm-12 card text-center" style="margin-bottom: 10px;">
                                <a href="http://www.ulleung.go.kr/tour/page.htm?mnu_uid=2061&" target="_blank" class="box">
                                <img class="card-img-top" src="{% static 'img/map/배.jpg' %}" alt="배시간&요금">
                                <div class="card-body" id="card">
                                    <div class="card-title">배시간 & 요금</div>
                                    <div class="card-sub">여객선 이용시 유의사항</div>
                                    <div class="card-link">상세보기</div>
                                </div>
                                </a>
                            </div>
                        </div>

                    </div>
                </div>
            </div>

        </div>
    </div>

{% endblock body %}

{% block js %}
{% endblock js %}