RC/rccoin/wallet/operate/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import *

from django.contrib.auth import views as auth_views

app_name = 'operate'

urlpatterns = [
#### main URL ##########################################################
    path('main/', main, name='main'),
#### 대시보드 URL #######################################################
    path('dashboard/', dashboard, name='dashboard'),
#### 공지사항 관리 URL ###################################################    
    path('notice/', manage_notice, name='notice'),
    path('notice/notice_add/', notice_edit, name='notice_add'),
    path('notice/notice_edit/<int:notice_id>', notice_edit, name='notice_edit'),
    path('notice/notice_activate/', notice_activate, name='notice_activate'),
#### 발행 관리 URL #######################################################    
    path('publish/', publish, name='publish'),
#### 거래 취소 관리 URL#######################################################
    path('cancel/', cancel, name='cancel'),
#### 네트워크 관리 URL ###################################################
    path('network/', network, name='network'),
#### 유저관리 URL ########################################################
    # path('users/', usersMyLV.as_view(), name='users'),
    path('users/', manageUser, name='users'),
    path('get_like/', get_like, name='get_like'),
#### 가맹점 URL ##########################################################
    path('approval/', manage_store_approval, name='approval'),
    path('get_approval/', get_approval, name='get_approval'),
##### 차트 URL ###########################################################
    path('stats/', manage_stats, name='stats'),
    path('stats/chartdata/', ChartData.as_view(), name='chartdata'),
    path('stats/west_stats/', west_stats, name='west_stats'),
    path('stats/north_stats/', north_stats, name='north_stats'),
    path('stats/wooleung_stats/', wooleung_stats, name='wooleung_stats'),
##### login_required ####################################################
    path('login_required/', login_required, name='login_required'),
    path('admin_logout/', admin_logout, name='admin_logout'),
]

RC/rccoin/wallet/rccoin/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import handler400, handler403, handler404, handler500
from . import views
handler400 = 'rccoin.views.error_400'
handler403 = 'rccoin.views.error_403'
handler404 = 'rccoin.views.error_404'
handler500 = 'rccoin.views.error_500'

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('accounts/', include('django.contrib.auth.urls')),

    path('', views.index, name='index'),
    path('<str:op>/done/', views.done, name='done'),
    
    path('intro/', views.intro, name='intro'),
    path('guide/', views.guide, name='guide'),
    path('map/', views.map, name='map'),

    path('operate/', include('operate.urls', namespace='operate')),
    path('account/', include('account.urls', namespace='account')),
    path('store/', include('store.urls', namespace='store')),
    path('wallet/', include('wallet.urls', namespace='wallet')),
    path('info/', include('info.urls', namespace='info')),
    path('board/', include('board.urls', namespace='board')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

RC/rccoin/wallet/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'wallet'

urlpatterns = [
    path('info/', views.read_wallet, name="info"),
    path('publish/', views.publish, name="publish"),
    path('remittance/', views.remittance, name="remittance"),
    path('payment/', views.payment, name="payment"),
    path('history/', views.get_history),
    path('receipt/', views.get_receipt),
    path('cancel/', views.cancel, name="cancel"),
    path('cancel_payment/', views.cancel_payment, name="cancel_payment"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

RC/rccoin/wallet/operate/models.py
from django.db import models
from store.models import Store
from wallet.models import Cancellation

# Create your models here.
# class Discount_rate(modes.Model):
#     pass

class ChartStat(models.Model):
    age = models.IntegerField(null=True)
    gender = models.CharField(max_length=3, null=True)
    store = models.ForeignKey(Store, null=True, on_delete=models.CASCADE)
    location = models.CharField(max_length=10, null=True)
    category = models.CharField(max_length=10, null=True)
    time = models.DateTimeField(auto_now=True, null=True)
    tx_id = models.CharField(max_length=100, null=True)
    amount = models.IntegerField(null=True)

class Comments(models.Model):
    text = models.CharField(max_length=100)

RC/rccoin/wallet/operate/views.py
from django.shortcuts import render, get_object_or_404, redirect, render_to_response
from django.http import HttpResponse, JsonResponse
from django.views.generic import ListView, DetailView, View,TemplateView

import requests

from info.models import Notice
from board.models import Comment, BoardLiker
from store.models import Photo, Store
from operate.models import ChartStat
from wallet.models import Cancellation
from django.db.models import Q, Sum

from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.contrib.auth import get_user_model

from info.forms import NoticeForm

from rest_framework.views import APIView
from rest_framework.response import Response

import json

Userchart = get_user_model()
#--------------------------------------로그인-----------------------------------------------#

def login_required(fn):
    def wrapper(*args, **kwargs):
        request = args[0]
        request_url = request.resolver_match.url_name
        key = 'admin_name'
        context = {}
        if key in request.session:
            if bool(request.session['admin_name'] == 'admin_server') & bool(request_url != 'network') & bool(request_url != 'dashboard'):
                return redirect('operate:dashboard')
            elif bool(request.session['admin_name'] == 'admin') & bool(request_url == 'network') & bool(request_url != 'dashboard'):
                return redirect('operate:dashboard')
            else:
                return fn(request)
        elif request.method == "POST":
            admin_name = request.POST.get('username', '')
            admin_pass = request.POST.get('password', '')
            user = authenticate(request, username=admin_name, password=admin_pass)
            if user is not None:
                request.session['admin_name'] = admin_name
                request.session.modified = True
                if bool(admin_name == 'admin_server') & bool(request_url != 'network') & bool(request_url != 'dashboard'):
                    return redirect('operate:dashboard')
                elif bool(admin_name == 'admin') & bool(request_url == 'network') & bool(request_url != 'dashboard'):
                    return redirect('operate:dashboard')
                else:
                    return fn(request)    
        else:
            context['main'] = 'main'
            return render(request, 'operate/manage_main.html', {'main': 'main'})
    return wrapper

def admin_logout(request, *args):
    request.session['admin_name'] = {}
    request.session.modified = True 
    logout(request)
    return redirect('operate:main')

#--------------------------------------메인-----------------------------------------------#

def main(request):
    key = 'admin_name'
    context = {}
    context['main'] = "main"
    if key in request.session:
        return redirect('operate:dashboard')
    else:
        if request.method == 'POST': # POST
            admin_name = request.POST.get('username', '')
            admin_pass = request.POST.get('password', '')
            user = authenticate(request, username=admin_name, password=admin_pass)
            if user is not None:
                request.session['admin_name'] = admin_name
                request.session.modified = True
                if admin_name != "":
                    return redirect('operate:dashboard')
                else:
                    return render(request, 'operate/manage_main.html', (context))
            else: 
                return render(request, 'operate/manage_main.html', (context))
        else: # GET
            return render(request, 'operate/manage_main.html', (context))

#--------------------------------------대시보드-----------------------------------------------#

@login_required
def dashboard(request):
    context = {}
    context['tx_cnt']              = get_tx_cnt()
    context['store_cnt']           = get_store_cnt()
    context['account_cnt']         = get_account_cnt()
    context['publish']             = 0 if get_publish_amount() == None else get_publish_amount()

    context['west_stats']          = 0 if get_total_location_tx(1) == None else get_total_location_tx(1)
    context['north_stats']         = 0 if get_total_location_tx(2) == None else get_total_location_tx(2)
    context['wooleung_stats']      = 0 if get_total_location_tx(3) == None else get_total_location_tx(3)
    context['west_stats']          = 0 if get_total_location_tx(2) == None else get_total_location_tx(2)
    context['north_stats']         = 0 if get_total_location_tx(3) == None else get_total_location_tx(3)
    context['wooleung_stats']      = 0 if get_total_location_tx(1) == None else get_total_location_tx(1)
    context['store_waiting_list']  = get_waiting_store()
    context['notice_list']         = get_notices()
    return render(request, 'operate/manage_dashboard.html', (context))

#--------------------------------------사용자관리-----------------------------------------------#
@login_required
def manageUser(request):
    context = {}
    data_list = []
    username = request.GET.get('keyword', '')
    context['users'] = User.objects.filter(Q(username__icontains=username) & ~Q(profile__type=0) & ~Q(profile__type=3)).order_by('id')
    
    return render(request, 'operate/manage_users.html', (context))

def get_like(request):
    user_id = request.GET.get('user_id', '')
    like = BoardLiker.objects.filter(liker = user_id)
    board = BoardLiker.objects.filter(board = user_id)
       
    context = {}
    context['like_cnt'] = len(like)
    context['board_cnt'] = len(board)
    json_format = json.dumps(context)
    return HttpResponse(json_format, content_type="application/json:charset=UTF-8") 
#-------------------------------------------------------------------------------------------#

#--------------------------------------가맹점승인관리-----------------------------------------------#
@login_required
def manage_store_approval(request):
    context = {}
    context['photos'] = Photo.objects.filter(store__status=1)
    return render(request, 'operate/manage_approval.html', (context))

def get_approval(request):
    store_id = request.GET.get('store_id', '')
    store = get_object_or_404(Store, id=store_id)
    userid = store.representative
    user = get_object_or_404(User, profile__user=userid)
    context = {}
    if store.status == 1:
        store.status = 2
        store.save()
        user.profile.type = 1
        user.save()
        context['result'] = 'y'
    else:
        context['result'] = 'n'

    json_format = json.dumps(context)
    return HttpResponse(json_format, content_type="application/json:charset=UTF-8") 
#-------------------------------------------------------------------------------------------#

#--------------------------------------공지사항관리-----------------------------------------------#
@login_required
def manage_notice(request):
    context = {}
    context['notice_list'] = Notice.objects.all()
    return render(request, 'operate/manage_notice.html', (context))

def notice_edit(request, notice_id=None):
    if notice_id:
        notice = get_object_or_404(Notice, pk=notice_id)
    else:
        notice = Notice()
    
    if request.method == 'POST': # POST
        form = NoticeForm(request.POST, instance=notice) 
        if form.is_valid():
            notice = form.save(commit=False)
            notice.save()
        return redirect('operate:notice')

    else: # GET 
        form = NoticeForm(instance=notice) 
        return render(request, 'operate/manage_notice_edit.html', dict(form=form, notice=notice))

def notice_activate(request):
    change_list = []
    change_list = request.GET.getlist('change_list[]', )
    
    context = {}
    try:
        for change_id in change_list:
            notice = get_object_or_404(Notice, id=change_id)
            if notice.status == "Y":
                notice.status = "N"
                notice.save()
            elif notice.status == "N":
                notice.status = "Y"
                notice.save()
            context['result'] = "success"
    except Exception as e:
        print(e)
        context['result'] = "fail"
            
    json_format = json.dumps(context)
    return HttpResponse(json_format, content_type="application/json:charset=UTF-8") 

#--------------------------------------발행이력관리-----------------------------------------------#
@login_required
def publish(request):
    context = {}
    publish_list = []
    publish_list = list(get_publish_amount()['publish_list'])
    total_publish = get_publish_amount()['total_publish']
    val = total_publish
    str(val)
    number = format(val,',')
    context['total_publish'] = number
    context['publish_list'] = publish_list
    return render(request, 'operate/manage_publish.html', (context))
#--------------------------------------거래취소관리-----------------------------------------------#
@login_required
def cancel(request):
    canceled_data = Cancellation.objects.all().order_by('-removed_date')
    cancel_data = {}
    data_list = []
    
    for datas in canceled_data:
        data = {}
        data['s_id'] = str(datas.s_id)
        data['txHash'] = datas.txHash
        data['amount'] = datas.amount
        data['comment'] = datas.comment
        data['removed_date'] = datas.removed_date
        data_list.append(data)
        
    cancel_data['cancel_data'] = data_list
    return render(request, 'operate/manage_cancel.html', (cancel_data))
#--------------------------------------네트워크 관리-----------------------------------------------#
@login_required
def network(request):
    context = {}
    context['default_block'] = get_default_block()[0]
    print(context)
    return render(request, 'operate/manage_network.html', (context))

##----------------------차트관리------------------------------------------------#

@login_required
def manage_stats(request):
    return render(request, 'operate/manage_stats.html', ({}))

##################북면#########################################

RC/rccoin/wallet/operate/templates/operate/basechart.html
{% load staticfiles %}
    {% include  'chart/css.html' %}
    {% include  'chart/bootstrap_defaults.html' %}
  </head>
  <body>
    <div class='container'>
    {% block content %}
    {% endblock content %}
    </div>
    {% include 'chart/js.html' %}
    <script>
    $(document).ready(function(){
      {% block jquery %}{% endblock %}
    })
    </script>
  </body>
</html>

RC/rccoin/wallet/operate/templates/operate/manage_dashboard.html
{% extends './base.html' %}
{% load staticfiles %}
{% block content %}
<style>
    .material-switch > input[type="checkbox"] {
        display: none;   
    }

    .material-switch > label {
        cursor: pointer;
        height: 0px;
        position: relative; 
        width: 40px;  
    }

    .material-switch > label::before {
        background: rgb(0, 0, 0);
        box-shadow: inset 0px 0px 10px rgba(0, 0, 0, 0.5);
        border-radius: 8px;
        content: '';
        height: 16px;
        margin-top: -8px;
        position:absolute;
        opacity: 0.3;
        transition: all 0.4s ease-in-out;
        width: 40px;
    }
    .material-switch > label::after {
        background: rgb(255, 255, 255);
        border-radius: 16px;
        box-shadow: 0px 0px 5px rgba(0, 0, 0, 0.3);
        content: '';
        height: 24px;
        left: -4px;
        margin-top: -8px;
        position: absolute;
        top: -4px;
        transition: all 0.3s ease-in-out;
        width: 24px;
    }
    .material-switch > input[type="checkbox"]:checked + label::before {
        background: inherit;
        opacity: 0.5;
    }
    .material-switch > input[type="checkbox"]:checked + label::after {
        background: inherit;
        left: 20px;
    }
    .table-border tr > td{
        font-family: Arial, Helvetica, sans-serif
    }
</style>
<input type="hidden" id="user_id">
<div class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-3 col-md-6 col-sm-6">
                <div class="card card-stats">
                    <div class="card-header card-header-success card-header-icon">
                        <div class="card-icon">
                            <i class="material-icons">compare_arrows</i>
                        </div>
                        <p class="card-category">트랜잭션</p>
                        <h3 class="card-title">{{ tx_cnt }}</h3>
                    </div>
                    <div class="card-footer">
                        <div class="stats">
                            <i class="material-icons">date_range</i>총 트랜잭션 수 입니다.
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-3 col-md-6 col-sm-6">
                <div class="card card-stats">
                    <div class="card-header card-header-warning card-header-icon">
                        <div class="card-icon">
                            <i class="material-icons">content_paste</i>
                        </div>
                        <p class="card-category">가맹점</p>
                        <h3 class="card-title">{{ store_cnt }}
                        </h3>
                    </div>
                    <div class="card-footer">
                        <div class="stats">
                            <i class="material-icons">store</i>총 가맹점 수 입니다.
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-3 col-md-6 col-sm-6">
                <div class="card card-stats">
                    <div class="card-header card-header-danger card-header-icon">
                        <div class="card-icon">
                            <i class="material-icons">account_balance_wallet</i>
                        </div>
                        <p class="card-category">계좌</p>
                        <h3 class="card-title">{{ account_cnt }}</h3>
                    </div>
                    <div class="card-footer">
                        <div class="stats">
                            <i class="material-icons">local_offer</i>총 계좌수입니다.
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-3 col-md-6 col-sm-6">
                <div class="card card-stats">
                    <div class="card-header card-header-info card-header-icon">
                        <div class="card-icon">
                            <i class="material-icons">local_atm</i>
                        </div>
                        <p class="card-category">발행량</p>
                        <h3 class="card-title">{{ publish.total_publish }}RC</h3>;
                        <h3 class="result"></h3>
                        
                    </div>
                    <div class="card-footer">
                        <div class="stats">
                            <i class="material-icons">local_atm</i>총 발행량 입니다.
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div style="float: left; width: 46%; margin-left: 2%; margin-right: 2%">
                <div class="card card-chart">
                    <div class="card-header card-header-success">
                        <div class="ct-chart" id="dailySalesChart"></div>
                    </div>
                    <div class="card-body">
                        <h4 class="card-title">전체 거래량</h4>
                        </p>
                        <p class="card-category">

                            <span class="text-success"><i class="material-icons">trending_up</i>
                                전년대비 증가율 <h4 class="section-data-result"></h4>
                            </span>


                    </div>
                    <div class="card-footer">
                        <div class="stats">
                            <i class="material-icons">local_offer</i><a href="{% url 'operate:stats' %}">통계보기</a><i
                                class="material-icons">subdirectory_arrow_left</i>
                        </div>
                    </div>
                </div>
            </div>
            <div style="float: right; width: 46%; margin-left: 2%; margin-right: 2%">
                <div class="card card-stats">
                    <div class="card-header card-header-warning card-header-icon">
                        <div class="card-icon">
                            <i class="material-icons">insert_chart</i>
                        </div>
                        <p class="card-category">서면</p>
                        <h3 class="card-title"> &nbsp; {{ west_stats }}
                        </h3>
                    </div>
                    <div class="card-footer">
                        <div class="stats">
                            <i class="material-icons">local_offer</i>
                            <a href="{% url 'operate:west_stats' %}">통계보기</a><i class="material-icons">subdirectory_arrow_left</i>
                        </div>
                    </div>
                </div>
                <div class="card card-stats">
                    <div class="card-header card-header-danger card-header-icon">
                        <div class="card-icon">
                            <i class="material-icons">insert_chart</i>
                        </div>
                        <p class="card-category">북면</p>
                        <h3 class="card-title"> &nbsp; {{ north_stats }}</h3>
                    </div>
                    <div class="card-footer">
                        <div class="stats">
                            <i class="material-icons">local_offer</i><a href="{% url 'operate:north_stats' %}">통계보기</a><i
                                class="material-icons">subdirectory_arrow_left</i>
                        </div>
                    </div>
                </div>
                <div class="card card-stats">
                    <div class="card-header card-header-info card-header-icon">
                        <div class="card-icon">
                            <i class="material-icons">insert_chart</i>
                        </div>
                        <p class="card-category">울릉읍</p>
                        <h3 class="card-title"> &nbsp; {{ wooleung_stats }}</h3>
                    </div>
                    <div class="card-footer">
                        <div class="stats">
                            <i class="material-icons">local_offer</i><a href="{% url 'operate:wooleung_stats' %}">통계보기</a><i
                                class="material-icons">subdirectory_arrow_left</i>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-6 col-md-12">
                <div class="card">
                    <div class="card-header card-header-tabs card-header-primary">
                        <div class="nav-tabs-navigation">
                            <div class="nav-tabs-wrapper">
                                <ul class="nav nav-tabs" data-tabs="tabs">
                                    <li class="nav-item">
                                        <a class="nav-link" href="#settings" data-toggle="tab">
                                            <i class="material-icons">cloud</i> 승인대기 가맹점
                                            <div class="ripple-container"></div>
                                        </a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="card-body">
                        <div class="tab-content">
                            <div class="tab-pane active" id="profile">
                                <ul class="list-group" style="inline:block;">
                                    {% for store in store_waiting_list %}
                                    {% if store.category == 1 %}
                                    <li class="list-group-item"><i class="material-icons">shopping_cart</i>
                                        {% endif %}
                                        {% if store.category == 2 %}
                                    <li class="list-group-item"><i class="material-icons">directions_bike</i>
                                        {% endif %}
                                        {% if store.category == 3 %}
                                    <li class="list-group-item"><i class="material-icons">hotel</i>
                                        {% endif %}
                                        {% if store.category == 4 %}
                                    <li class="list-group-item"><i class="material-icons">local_dining</i>
                                        {% endif %}
                                        &nbsp;&nbsp; | &nbsp;&nbsp;{{ store.name }} &nbsp;&nbsp;|&nbsp;&nbsp;
                                        {{store.corporate_number }} &nbsp;&nbsp;|&nbsp;&nbsp; {{ store.modified_date }}
                                    </li>
                                    {% endfor %}
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-6 col-md-12">
                <div class="card">
                    <div class="card-header card-header-warning">
                        <h4 class="card-title">공지사항</h4>
                        <p class="card-category">공지사항 미리보기</p>
                    </div>
                    <div class="card-body table-responsive">
                        <table class="table table-hover table-border">
                            <thead class="text-warning" align="center">
                                <th>Index</th>
                                <th>Title</th>
                                <th>Writer</th>
                                <th>Create</th>
                                <th>Modify</th>
                                <th>Status</th>
                            </thead>
                            <tbody>
                                {% for notice in notice_list %}
                                <tr align="center">
                                    <td>{{ notice.id }}</td>
                                    <td>{{ notice.title }}</td>
                                    <td>{{ notice.writer }}</td>
                                    <td>{{ notice.create_date }}</td>
                                    <td>{{ notice.modify_date }}</td>
                                    <td>{{ notice.status }}</td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    $(document).ready(function () {
        var endpoint = '{% url "operate:chartdata" %}'
        var defaultData = []
        var labels_second = []
        var labels = []


        $.ajax({
            method: "GET",
            url: endpoint,
            success: function (data) {

                all_labels = data.all_labels
                all_default = data.all_default

                var all = ((all_default[4] - all_default[3]) / (all_default[3] + 1) * 100) + '%'
                var result = all.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ",");
                
                $('.section-data-result').text(result)
                
                },
            error: function (error_data) {
                console.log("error")
                console.log(error_data)
            }
        })
    })
</script>
{% endblock content %}

RC/rccoin/wallet/operate/templates/operate/manage_notice_edit.html
{% extends './base.html' %}
{% block content %}
<style>
    .note-editable{
      height: 238.3px;
    }
</style>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.js"></script>
<script src="https://netdna.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.9/summernote.js"></script>
<link href="https://netdna.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.css" rel="stylesheet">
<link href="https://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.9/summernote.css" rel="stylesheet">
  <div class="content">
    <div class="container-fluid"> 
      <div class="row">
        <div class="col-md-12">
          <div class="card">
            <div class="card-header card-header-success">
              <h4 class="card-title "><i class="material-icons">library_books</i>&nbsp;공지사항 관리</h4>
              <p class="card-category">this is the page of managing notices</p>
            </div>
            <div class="card-body">
              <div class="table-responsive">
                {% if notice.id %}
                    <form action="{% url 'operate:notice_edit' notice_id=notice.id %}" method="POST">
                {% else %}
                    <form action="{% url 'operate:notice_add' %}" method="POST">
                {% endif %}
                {% csrf_token %}
                <fieldset class="aligned">
                    {{ form.title.label_tag }} {{ form.title }}
                    <hr>
                    {{ form.content|safe }}
                </fieldset>
                    <div class="form-group row btn_group" style="margin-left: -382px;">
                        <div class="offset-md-3 col-md-9">
                            <input type="submit" class="btn" value="제출">
                            <a class="btn" href="{% url 'operate:notice' %}">돌아가기</a>
                        </div>
                    </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script type="text/javascript">
    $('textarea').attr('id', 'summernote');
    $('#summernote').summernote();
  </script>
{% endblock content %}      