RC/rccoin/wallet/account/urls.py
from django.urls import path
from . import views

app_name = 'account'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('forget_id/', views.forget_id, name='forget_id'),
    path('forget_pwd/', views.forget_pwd, name='forget_pwd'),
    path('agreement/', views.agreement, name='agreement'),
    path('chk_username/', views.chk_username),
    path('chk_password/', views.chk_password),
    path('signup/', views.signup, name='signup'),
    path('info/', views.get_myinfo, name='info'),
    path('<str:op>/identity/', views.identity, name='identity'),
    path('<str:op>/identity/<int:s_id>/', views.identity, name='identity2'),
    path('edit/', views.account_edit, name='edit'),
    path('chg_pwd/', views.change_pwd, name='chg_pwd'),
]

RC/rccoin/wallet/rccoin/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import handler400, handler403, handler404, handler500
from . import views
handler400 = 'rccoin.views.error_400'
handler403 = 'rccoin.views.error_403'
handler404 = 'rccoin.views.error_404'
handler500 = 'rccoin.views.error_500'

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('accounts/', include('django.contrib.auth.urls')),

    path('', views.index, name='index'),
    path('<str:op>/done/', views.done, name='done'),
    
    path('intro/', views.intro, name='intro'),
    path('guide/', views.guide, name='guide'),
    path('map/', views.map, name='map'),

    path('operate/', include('operate.urls', namespace='operate')),
    path('account/', include('account.urls', namespace='account')),
    path('store/', include('store.urls', namespace='store')),
    path('wallet/', include('wallet.urls', namespace='wallet')),
    path('info/', include('info.urls', namespace='info')),
    path('board/', include('board.urls', namespace='board')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

RC/rccoin/wallet/store/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from .views import *

app_name = 'store'

urlpatterns = [
    path('apply/', edit_store, name='apply'),
    path('info/', get_myStore, name='info'),
    path('edit/', edit_store, name='edit'),
    path('<int:s_id>/delete/', del_store, name='delete'),
    path('qrcode/', get_qrcode, name='qrcode'),
    path('list/', StorePV.as_view(), name='store_list'),
    path('list/filter/<int:loc>/', filteredStoresPV.as_view(), name='filteredStores'),
    path('list/detail/<int:store_id>/', detailView, name='filteredStoresDetail')

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

RC/rccoin/wallet/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'wallet'

urlpatterns = [
    path('info/', views.read_wallet, name="info"),
    path('publish/', views.publish, name="publish"),
    path('remittance/', views.remittance, name="remittance"),
    path('payment/', views.payment, name="payment"),
    path('history/', views.get_history),
    path('receipt/', views.get_receipt),
    path('cancel/', views.cancel, name="cancel"),
    path('cancel_payment/', views.cancel_payment, name="cancel_payment"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

RC/rccoin/wallet/store/models.py
from __future__ import unicode_literals
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.contrib.auth.models import User
from django.urls import reverse
from .fields import ThumbnailImageField
import os

# Create your models here.

class Location(models.Model):
    loc = models.CharField(max_length=20)

    def __str__(self):
        return self.loc

class Category(models.Model):
    domain = models.CharField(max_length=20)

    def __str__(self):
        return self.domain

def upload_path_handler(instance, filename):
    return "store/store_{id}/{file}".format(id=instance.store.id, file=filename)

@python_2_unicode_compatible
class Store(models.Model):
    name = models.CharField(max_length=100, null=True)
    corporate_number = models.CharField(max_length=12, null=True)
    representative = models.ForeignKey(User, null=True, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, null=True, on_delete=models.CASCADE)
    location = models.ForeignKey(Location, null=True, on_delete=models.CASCADE)
    address = models.CharField(max_length=100, null=True, default='-')
    phone_number = models.CharField(max_length=15, null=True, default='-')
    url = models.CharField(max_length=100, null=True, default='-')
    opening_hour = models.CharField(max_length=2, null=True)
    opening_minute = models.CharField(max_length=2, null=True)
    closing_hour = models.CharField(max_length=2, null=True)
    closing_minute = models.CharField(max_length=2, null=True)
    description = models.TextField(blank=True)
    registered_date = models.DateTimeField(auto_now_add=True, null=True)
    modified_date = models.DateTimeField(auto_now=True)
    status = models.IntegerField(default=1)

    def __str__(self):
        return self.name

class Photo(models.Model):
    store = models.ForeignKey('Store', on_delete=models.CASCADE)
    image = ThumbnailImageField(upload_to=upload_path_handler, null=True)
    upload_date = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['store']

    def __str__(self):
        return self.store.name

RC/rccoin/wallet/store/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.views.generic import ListView, DetailView, View
from .models import Category, Location, Store, Photo
from account.models import Profile
import json, datetime

# Create your views here.

# 가맹점 신청 / 정보수정
@login_required
def edit_store(request):
    try:
        store = (Store.objects.filter(Q(representative_id=request.user.pk) & ~Q(status=3)))[0]
        photo = (Photo.objects.filter(Q(store_id=store.pk)))[0]
    except:
        store = Store()
        photo = Photo()

    if request.method == 'POST':
        store.name = request.POST.get('name', None)
        store.representative = request.user
        store.corporate_number = request.POST.get('corporate_number', None)
        store.location = get_object_or_404(Location, id=request.POST.get('location', 1))
        store.category = get_object_or_404(Category, id=request.POST.get('category', 1))
        store.phone_number = request.POST.get('phone_number', None)
        store.url = request.POST.get('url', None)
        store.address = request.POST.get('address', None)
        store.opening_hour = request.POST.get('opening_hour', None) 
        store.opening_minute = request.POST.get('opening_minute', None)
        store.closing_hour = request.POST.get('closing_hour', None)
        store.closing_minute = request.POST.get('closing_minute', None)
        store.description = request.POST.get('description', None)
        store.status = 1
        store.save()
        
        photo.store_id = store.pk
        photo.image = request.FILES['image']
        photo.save()
        
        profile = get_object_or_404(Profile, user_id=request.user.pk)
        profile.type = 1
        profile.save()

        return redirect('store:info')
    else:
        category = Category.objects.all().order_by('id')
        category_list = []
        for domain in category:
            temp = {
                'id' : domain.id,
                'domain' : domain.domain   
            }
            category_list.append(temp)
        categorys = {
            'category_list' : category_list
        }
        json_category = json.dumps(categorys)

        location = Location.objects.all().order_by('id')
        location_list = []
        for loc in location:
            temp = {
                'id' : loc.id,
                'loc' : loc.loc   
            }
            location_list.append(temp)
        locations = {
            'location_list' : location_list
        }
        json_location = json.dumps(locations)

        data = {
            'store' : store,
            'photo' : photo,
            'categorys' : json_category,
            'locations' : json_location
        }
        return render(request, 'store/store_edit.html', data)

# 카테고리 리스트 가져오기
def get_categorys():
    categorys = Category.objects.all()
    domain_list = []
    for domain in categorys:
        domain_list.append(domain)
    return domain_list

# 로케이션 리스트 가져오기
def get_locations():
    locations = Location.objects.all()
    location_list = []
    for loc in locations:
        location_list.append(loc)
    return location_list

# 내 가맹점 정보 조회
@login_required
def get_myStore(request):
    user = request.user
    store = (Store.objects.filter(Q(representative_id = user.pk) & ~Q(status=3)))[0]
    photo = (Photo.objects.filter(Q(store_id=store.pk)))[0]
    domain = get_categorys()
    loc = get_locations()
    status = ['승인대기중', '승인됨']

    data = {
        'store' : store,
        'photo' : photo,
        'status': status[store.status-1],
        'domain': domain[store.category_id-1],
        'loc'   : loc[store.location_id-1],
        'rdate' : (store.registered_date).strftime('%Y-%m-%d %H:%M:%S'),
        'mdate' : (store.modified_date).strftime('%Y-%m-%d %H:%M:%S')
    }
    return render(request, 'store/store_info.html', data)

# 가맹점 삭제
@login_required
def del_store(request, s_id):
    store = (Store.objects.filter(Q(pk=s_id) & ~Q(status=3)))[0]
    if store.representative_id == request.user.pk:
        store.status = 3
        store.save()
        profile = get_object_or_404(Profile, user=request.user)
        profile.type = 2
        profile.save()
        # 삭제 성공
        return redirect('/store1/done')
    else:
        return redirect('/store2/done')

# QR Code 페이지 생성
@login_required
def get_qrcode(request):
    store = (Store.objects.filter(Q(representative=request.user) & Q(status=2)))[0]
    return render(request, 'store/store_QRcode.html', dict(store=store))
        
# 가맹점 리스트
class StorePV(ListView):
    model=Photo
    paginate_by = 9
    context_object_name = 'photos'
    template_name = 'store_list.html'

    def get_context_data(self, **kwargs):
        context = super(StorePV, self).get_context_data(**kwargs)
        paginator = context['paginator']
        page_numbers_range = 5  # Display only 5 page numbers
        max_index = len(paginator.page_range)
        
        page = self.request.GET.get('page')
        self.request.session['page'] = page
        current_page = int(page) if page else 1
        if 'filter' in self.request.session:
            del self.request.session['filter']
        if 'keyword' in self.request.session:
            del self.request.session['keyword']
            
        start_index = int((current_page - 1) / page_numbers_range) * page_numbers_range
        end_index = start_index + page_numbers_range
        if end_index >= max_index:
            end_index = max_index
        page_range = paginator.page_range[start_index:end_index]
        context['page_range'] = page_range
        return context

    def get_queryset(self, **kwargs):
        queryset = Photo.objects.filter(Q(store__status=2)) # filter returns a list so you might consider skip except part
        return queryset

# 가맹점 리스트(필터)
class filteredStoresPV(ListView):
    model=Photo
    paginate_by = 9
    context_object_name = 'photos'
    template_name = 'store_list.html'
        
    def get_context_data(self, **kwargs):
        context = super(filteredStoresPV, self).get_context_data(**kwargs)
        paginator = context['paginator']
        page_numbers_range = 5  # Display only 5 page numbers
        max_index = len(paginator.page_range)

        page = self.request.GET.get('page')
        if page:
            self.request.session['page'] = page
        else:
            self.request.session['page'] = 1

        current_page = int(page) if page else 1

        start_index = int((current_page - 1) / page_numbers_range) * page_numbers_range
        end_index = start_index + page_numbers_range
        if end_index >= max_index:
            end_index = max_index

        page_range = paginator.page_range[start_index:end_index]
        context['page_range'] = page_range

        return context

    def get_queryset(self, **kwargs):
        loc = self.kwargs.get('loc',None)
        self.request.session['filter'] = loc
        if loc == 4:
            search_query = self.request.GET.get('keyword', None)
            self.request.session['keyword'] = search_query
            queryset = Photo.objects.filter(Q(store__name__icontains=search_query) & Q(store__status=2) ) # filter returns a list so you might consider skip except part
        else:
            if 'keyword' in self.request.session:
                del self.request.session['keyword']
            queryset = Photo.objects.filter(Q(store__status=2) & Q(store__location=loc))
        return queryset

# 가맹점 가맹점 상세보기
def detailView (request, store_id=None):
    store = get_object_or_404(Store, pk=store_id)
    photo = get_object_or_404(Photo, store_id=store.pk)
    return render(request, 'store/store_list_detail.html', dict(store=store, photo=photo))

RC/rccoin/wallet/store/templates/store/photo_list.html
{% extends 'base.html' %}

{% block head %}
{% load staticfiles %}
{% endblock head %}

{% block css %}
.card{float: left; width:100%;}
.title-small { color: #495057; font-size: 1rem; font-weight: 600; line-height: 23px; padding: 10px; margin-bottom: 10px; border: 1px solid #0000001a; border-radius: 0px 0px 5px 5px;}
.title-large a, .title-small a, .title-x-small a{color: inherit}
.banner-sec{float: left; width: 100%; background: #EBEBEB}
.card-block{padding:0 10px 10px;}
.card-text{margin: 0}
.text-time{color: #ff0000; font-weight: 600;}
.banner-sec .card-img-overlay{padding: 0; top: 3px; left: 7px; height: 20%}
.card-img-overlay{padding: 0.5rem 1.5rem;}

#search {float: right; margin-top: 9px; width: 250px;}
.search {padding: 5px 0; width: 230px; height: 30px; position: relative; left: 10px; float: left; line-height: 22px;}
.search input {background: #d0d0d0; border: medium none; border-radius: 3px 0 0 3px; float: left; height: 36px; line-height: 18px; margin-left: 210px; padding: 0 9px; position: absolute; top: -3px; width: 0; -webkit-transition: all 0.7s ease-in-out; -moz-transition: all 0.7s ease-in-out;
-o-transition: all 0.7s ease-in-out; transition: all 0.7s ease-in-out;}
.search:hover input, .search input:focus { width: 200px; margin-left: 0px; background: #d0d0d0;}
.top-nav .btn {position: absolute;right: 0;top: -3px;border-radius:3px;}
.action-sec{width:100%; float:left; background:#222}
.action-box{float:left; width:100%; text-align:center;}
.action-box h2{color:#fff; font-size:20px;}

.img-fluid {
    border-radius: 5px 5px 0px 0px;
}
.badge1 {
    color: #fff;
    background-color: #c82333;
    border-color: #bd2130;
}
.badge2 {
    color: #212529;
    background-color: #ffc107;
    border-color: #ffc107;
}
.badge3 {
    color: #fff;
    background-color: #28a745;
    border-color: #28a745;
}
@media (max-width: 992px) {
    .margin-top {
        margin-top: 10px;
    }
}
{% endblock css %}
{% block body %}


    <!-- Title -->
    <div id="contents" class="page-header">
        <div class="container">
            <div class="row page-title">
                <a>가맹점</a>
            </div>
        </div>
    </div>
    
    <!-- Filter button -->
    <div id="contents">
        <div class="container">
            <div class="row justify-content-center page">
                <div class="col-md card">
                    <div class="card-body">
                        <div class="row">
                            <h5 class="col-lg-4 col-md-12 col-sm-12 card-subtitle"><a style="color:#00c746;">|</a> 가맹점 목록</h5>
                            
                            <div class="col-lg-4 col-md-12 col-sm-12 margin-top" style="text-align: right;">
                                <form id="searchform" action="{% url 'store:filteredStores' 4 %}" method="GET" class="row" style="margin: 0;">
                                    <input type="text" id="keyword" name="keyword" class="form-control" style="width: 75%;" required placeholder="검색어" />
                                    <input type="submit" value="검색" class="btn btn-primary form-control" style="width: 25%;" />
                                </form>
                            </div>

                            <div class="col-lg-4 col-md-12 col-sm-12 btn-group margin-top">
                                <a href="{% url 'store:store_list' %}?page=1" class="btn btn-primary">전체지역</a>
                                <a href="{% url 'store:filteredStores' 3 %}?page=1" class="btn btn-success" />북면</a>
                                <a href="{% url 'store:filteredStores' 2 %}?page=1" class="btn btn-warning" />서면</a>
                                <a href="{% url 'store:filteredStores' 1 %}?page=1" class="btn btn-danger" />울릉읍</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            
            <div class="row justify-content-center page">
                <div class="col-md card">
                    <div class="card-body">
                        <div class="row">
                            {% for photo in photos %}
                            <a href="{% url 'store:filteredStoresDetail' photo.store_id %}">
                                <div class="col-lg-4 col-md-6 col-sm-12 card"> <img class="img-fluid" src="/media/{{ photo.image }}" alt="">
                                    <div class="card-img-overlay"><span class="badge badge-pill badge{{ photo.store.location.id }}">{{ photo.store.location }}</span> </div>
                                    <div class="card-body">
                                        <div class="news-title">
                                            <h2 class=" title-small"><a href="#"><img src="{% static 'img/store.png' %}"> {{ photo.store }}</a> <sup class="text-primary">{{ photo.store.category }}</sup></h2>
                                        </div>
                                    </div>
                                </div>
                            </a>
                            {% endfor %}
                        </div>
                            
                        <div class="row justify-content-center">
                            {% if is_paginated %}
                            <nav>
                                <ul class="pagination">
                                {% if page_obj.has_previous %}
                                    <li>
                                    {% if request.session.keyword %}
                                    <a class="page-item" href="?keyword={{ request.session.keyword }}&page={{ page_obj.previous_page_number }}">
                                    {% else %}
                                    <a class="page-item" href="?page={{ page_obj.previous_page_number }}">
                                    {% endif %}
                                        <span class="page-link">Prev</span>
                                    </a>
                                    </li>
                                {% else %}
                                    <li class="page-item disabled">
                                    <a href="">
                                        <span class="page-link">Prev</span>
                                    </a>
                                    </li>
                                {% endif %}

                                {% for page in page_range %}
                                    <li {% if page == page_obj.number %} class="page-item active"{% endif %}>
                                    {% if request.session.keyword %}
                                    <a href="?keyword={{ request.session.keyword }}&page={{ page }}" class="page-link">{{ page }}</a>
                                    {% else %}
                                    <a href="?page={{ page }}" class="page-link">{{ page }}</a>
                                    {% endif %}
                                    </li>
                                {% endfor %}

                                {% if page_obj.has_next %}
                                    <li class="page-item">
                                    {% if request.session.keyword %}
                                    <a href="?keyword={{ request.session.keyword }}&page={{ page_obj.next_page_number }}" class="page-link">
                                    {% else %}
                                    <a href="?page={{ page_obj.next_page_number }}" class="page-link">
                                    {% endif %}
                                        <span>Next</span>
                                    </a>
                                    </li>
                                {% else %}
                                    <li {% if not page_obj.has_next %}class="page-item disabled"{% endif %}>
                                    <a href="#">
                                        <span class="page-link">Next</span>
                                    </a>
                                    </li>
                                {% endif %}
                                </ul>
                            </nav>
                            {% endif %}
                        </div>        
                    </div>
                </div>

            </div>
        </div>
    </div>

{% endblock body %}

{% block js %}
<script src="{% static 'js/search.js' %}"></script>
{% endblock js %}

RC/rccoin/wallet/store/templates/store/store_info.html
{% extends 'base.html' %}

{% block head %}
{% load staticfiles %}
{% endblock head %}

{% block css %}
@media (max-width: 765px) {
    .btn-group {
        margin-top: 10px;
    }
}
{% endblock css %}
{% block body %}


    <!-- Title -->
    <div id="contents" class="page-header">
        <div class="container">
            <div class="row page-title">
                <a>가맹점 관리</a>
            </div>
        </div>
    </div>
    
    <div id="contents">
        <div class="container">
            <div class="row justify-content-center page">
                <div class="col-md card">
                    <div class="card-body">
                        <h5 class="card-subtitle"><a style="color:#00c746;">|</a> 가맹점 정보</h5>
                    </div>
                </div>
            </div>
            
            <div class="row justify-content-center page">
                <div class="col-md card">
                    <div class="card-body">

                        <!-- MyStore info -->
                        <div class="row">
                            <div class="col-md-3">
                                <div class="profile-img">
                                    <img src="/media/{{ photo.image }}" class="img-responsive" alt="">
                                </div>

                                <div class="row2 justify-content-center" style="margin-top: 10px">
                                    <a href="{% url 'account:identity' 's_edit' %}" class="btn btn-success" style="margin: 0px 5px 0px 5px;">수정</a>
                                    <a href="{% url 'account:identity2' op='s_del' s_id=store.id %}" class="btn btn-danger" style="margin: 0px 5px 0px 5px;">삭제</a>
                                    {% if store.status == 2 %}
                                    </form>
                                    <form action="{% url 'store:qrcode' %}" method="POST" target="_blank">
                                        {% csrf_token %}
                                        <input type="text" id="s_id" name="s_id" hidden></input>
                                        <button type="submit" id="btn_qr" class="btn btn-warning" style="margin: 0px 5px 0px 5px;">QR코드</button>
                                    </form>
                                    {% endif %}
                                </div>

                                <hr class="d-block d-sm-none">
                            </div>

                            <div class="col-md-9">
                                <div class="name-wrapper">
                                    <div class="profile-usertitle-name">{{ store.name }}</div>
                                    <div class="profile-usertitle-job">(사업자등록번호) {{ store.corporate_number }}</div>
                                </div>

                                <div class="row">
                                    <div class="col-md-4">
                                        <div class="personal-details">
                                            <small>등록업종</small>
                                            <strong>{{ domain }}</strong>
                                        </div>
                                    </div>
                                    <div class="col-md-4">
                                        <div class="personal-details">
                                            <small>등록지역</small>
                                            <strong>{{ loc }}</strong>
                                        </div>
                                    </div>
                                    <div class="col-md-4">
                                        <div class="personal-details">
                                            <small>영업시간</small>
                                            <strong>{{ store.opening_hour }}:{{ store.opening_minute }}-{{ store.closing_hour }}:{{ store.closing_minute }}</strong>
                                        </div>
                                    </div>
                                </div>
                                
                                <div class="row">
                                    <div class="col-md-4">
                                        <div class="personal-details">
                                            <small>홈페이지</small>
                                            <strong>{{ store.url }}</strong>
                                        </div>
                                    </div>
                                    <div class="col-md-4">
                                        <div class="personal-details">
                                            <small>연락처</small>
                                            <strong>{{ store.phone_number }}</strong>
                                        </div>
                                    </div>
                                    <div class="col-md-4">
                                        <div class="personal-details">
                                            <small>승인상태</small>
                                            <strong>{{ status }}</strong>
                                        </div>
                                    </div>
                                </div>
                                
                                <div class="row">
                                    <div class="col-md-12">
                                        <div class="personal-details">
                                            <small>주소</small>
                                            <strong>{{ store.address }}</strong>
                                        </div>
                                    </div>
                                </div>

                                
                                <div class="row">
                                    <div class="col-md-4">
                                        <div class="personal-details">
                                            <small>등록일</small>
                                            <strong>{{ rdate }}</strong>
                                        </div>
                                    </div>
                                    <div class="col-md-4">
                                        <div class="personal-details">
                                            <small>수정일</small>
                                            <strong>{{ mdate }}</strong>
                                        </div>
                                    </div>
                                    <div class="col-md-4">
                                        <div class="personal-details">
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>


    <!-- Filter button -->
    <div id="contents">
        <div class="container">
            <div class="row justify-content-center page">
                <h5 class="col-md-8 card-subtitle"><a style="color:#00c746;">|</a> 거래 이력</h5>
                
                <div class="col-md-4 btn-group">
                    <button type="button" class="btn btn-primary" onclick="get_receipt(1, 0)">전체</button>
                    <button type="button" class="btn btn-danger" onclick="get_receipt(1, 1)">결제</button>
                    <button type="button" class="btn btn-secondary" onclick="get_receipt(1, 2)">취소</button>
                </div>
            </div>
        </div>
    </div>


    <!-- History -->
    <div id="contents">
        <div class="container">
            <div class="row justify-content-center page">
                <table class="table table-filter">
                    <tbody id="receipt"></tbody>                            
                </table>
                <div class="row2 justify-content-center">
                    <nav aria-label="page navigation">
                        <ul id="page-area" class="pagination"></ul>
                    </nav>
                </div>
            </div>
        </div>
    </div>
        

{% endblock body %}

{% block js %}
<script src="{% static 'js/receipt.js' %}"></script>
{% endblock js %}