RC/rccoin/wallet/board/urls.py
from django.contrib import admin
from django.urls import path, include

from .views import BoardLV
from .views import BoardDV
from .views import *

app_name = 'board'

urlpatterns = [
    path('list/', BoardLV.as_view(), name='list'),
    path('read/<int:pk>/', BoardDV.as_view(), name='read'),
    path('add/', board_edit, name='add'),
    path('edit/<int:board_id>/', board_edit, name='edit'),
    path('delete/<int:board_id>/', board_delete, name='delete'),
    path('comment/', get_comment, name='comment'),
    path('chg/', chg_board, name='chg'),
    path('write_comment/', write_comment, name='write_comment'),
    path('add_like/', add_like, name='add_like'),

    ## external
    path('board_search/', board_search, name='board_search'),
]

RC/rccoin/wallet/rccoin/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import handler400, handler403, handler404, handler500
from . import views
handler400 = 'rccoin.views.error_400'
handler403 = 'rccoin.views.error_403'
handler404 = 'rccoin.views.error_404'
handler500 = 'rccoin.views.error_500'

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('accounts/', include('django.contrib.auth.urls')),

    path('', views.index, name='index'),
    path('<str:op>/done/', views.done, name='done'),
    
    path('intro/', views.intro, name='intro'),
    path('guide/', views.guide, name='guide'),
    path('map/', views.map, name='map'),

    path('operate/', include('operate.urls', namespace='operate')),
    path('account/', include('account.urls', namespace='account')),
    path('store/', include('store.urls', namespace='store')),
    path('wallet/', include('wallet.urls', namespace='wallet')),
    path('info/', include('info.urls', namespace='info')),
    path('board/', include('board.urls', namespace='board')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

RC/rccoin/wallet/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'wallet'

urlpatterns = [
    path('info/', views.read_wallet, name="info"),
    path('publish/', views.publish, name="publish"),
    path('remittance/', views.remittance, name="remittance"),
    path('payment/', views.payment, name="payment"),
    path('history/', views.get_history),
    path('receipt/', views.get_receipt),
    path('cancel/', views.cancel, name="cancel"),
    path('cancel_payment/', views.cancel_payment, name="cancel_payment"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

RC/rccoin/wallet/board/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.urls import reverse

# Create your models here.
# author = models.ForeignKey(settings.AUTH_USER_MODEL)

User = get_user_model()

class Board(models.Model):
    title = models.CharField('TITLE', max_length=100)
    content = models.TextField('CONTENT')
    writer = models.ForeignKey(User, null=True, on_delete=models.CASCADE)
    create_date = models.DateTimeField('CREATE_DATE', auto_now_add=True)
    modify_date = models.DateTimeField('MODIFY_DATE', auto_now=True)
    category = models.CharField('CATEGORY', max_length=10)
    count = models.IntegerField('COUNT', default=0)
    recommend = models.IntegerField('RECOMMEND', default=0)
    status = models.CharField('STATUS', max_length=1, default='Y')

    class Meta:
        ordering = ('-create_date',)
    def get_absolute_url(self):
        return reverse("board:read", args=(self.pk,))

class Comment(models.Model):
    board_id = models.ForeignKey(Board, on_delete=models.CASCADE)
    writer = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField('CONTENT')
    create_date = models.DateTimeField('CREATE_DATE', auto_now_add=True)
    modify_date = models.DateTimeField('MODIFY_DATE', auto_now=True)
    status = models.CharField('STATUS', max_length=1, default='Y')

class BoardLiker(models.Model):
    liker = models.ForeignKey(User, null=True, on_delete=models.CASCADE)
    board = models.ForeignKey(Board, null=True, on_delete=models.CASCADE)

RC/rccoin/wallet/board/forms.py
from django.forms import ModelForm

from board.models import Board

class BoardForm(ModelForm):
    class Meta:
        model = Board
        fields = ('title', 'content')

RC/rccoin/wallet/board/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from django.views.generic import ListView, DetailView
from django.contrib.auth.models import User

import json

from board.models import Board, Comment, BoardLiker
from django.db.models import Q

from board.forms import BoardForm

import datetime
from datetime import datetime as dt
from datetime import timedelta

from django.core.paginator import Paginator
# Create your views here.

class BoardLV(ListView):
    
    def get_queryset(self):
        if self.request.user.username == '':
            queryset = Board.objects.filter(category=1)
            try:
                if self.request.COOKIES['from'] != 'not_intro':
                    self.request.COOKIES['is_intro'] = 'intro'
                    self.request.COOKIES['from'] = ''
            except:
                self.request.COOKIES['is_intro'] = 'intro'

        else:
            user = get_object_or_404(User, username=self.request.user.username)
            self.user_type = user.profile.type
            queryset = Board.objects.filter(category=1)
            try:
                if self.request.COOKIES['from'] != 'not_intro':
                    self.request.COOKIES['is_intro'] = 'intro'
                    self.request.COOKIES['from'] = ''
            except:
                self.request.COOKIES['is_intro'] = 'intro'
        return queryset

class BoardDV(DetailView):
    model = Board

    def get_context_data(self, **kwargs):
        context = super(BoardDV, self).get_context_data(**kwargs)

        added = self.object.count + 1
        board = get_object_or_404(Board, id=self.object.id)
        board.count = added
        board.save()

        comment_cnt = 0

        try:
            comment = Comment.objects.filter(board_id=self.object.id)
            comment_cnt = len(comment)
        except Exception as e:
            comment_cnt = 0

        print(comment_cnt)
        context['object'] = self.object
        context['comment_cnt'] = comment_cnt
        return context

def board_edit(request, board_id=None):

    user = request.user.pk
    user_type = request.user.profile.type

    if board_id:
        board = get_object_or_404(Board, pk=board_id)
    else:
        board = Board()

    if request.method == "POST":
        # POST 된 request 데이터를 가지고 Form 생성
        form = BoardForm(request.POST, instance=board)
        if form.is_valid():
            board = form.save(commit=False)
            board.board_id = Board(board_id)
            board.writer = User(user)
            if not board_id:
                board.category = user_type
            board.save()
            # request 없이 페이지 이동만 한다.
        return redirect('board:list')
    else:
        # book instance에서 Form 생성
        form = BoardForm(instance=board)
        # 사용자의 request를 가지고 이동한다.
        return render(request, 'board/board_edit.html', dict(form=form, board=board))

def board_delete(request, board_id):
    board = get_object_or_404(Board, pk=board_id)
    board.delete()
    return redirect('board:list')

def get_comment(request):
    now = dt.now()
    board_id = request.GET.get('board_id', )

    comments = Comment.objects.filter(board_id=board_id)

    data_list = []
    for li in comments:

        temp = {}
        temp['board_id'] = li.board_id.id
        temp['writer'] = str(li.writer.profile.user)
        temp['content'] = li.content
        if(now.timetuple().tm_year != li.modify_date.timetuple().tm_year):
            temp['time_diff'] = "{} 년 전 ".format(now.timetuple().tm_year - li.modify_date.timetuple().tm_year)
        elif(now.timetuple().tm_mon != li.modify_date.timetuple().tm_mon):
            temp['time_diff'] = "{} 달 전 ".format(now.timetuple().tm_mon - li.modify_date.timetuple().tm_mon)
        elif(now.timetuple().tm_mday != li.modify_date.timetuple().tm_mday):
            temp['time_diff'] = "{} 일 전 ".format(now.timetuple().tm_mday - li.modify_date.timetuple().tm_mday)
        elif (now.timetuple().tm_hour != li.modify_date.timetuple().tm_hour):
            temp['time_diff'] = "{} 시간 전 ".format(now.timetuple().tm_hour - li.modify_date.timetuple().tm_hour)
        elif (now.timetuple().tm_min != li.modify_date.timetuple().tm_min):
            temp['time_diff'] = "{} 분 전 ".format(now.timetuple().tm_min - li.modify_date.timetuple().tm_min)
        else:
            temp['time_diff'] = "방금"
        print("now: ", now.timetuple())
        print("modify: ", li.create_date.timetuple())
        temp['modify_date'] = str(li.modify_date)
        temp['status'] = li.status
        data_list.append(temp)
    json_format = json.dumps(data_list)

    return HttpResponse(json_format, content_type="application/json:charset=UTF-8")

def chg_board(request):
    board_type = request.GET.get('board_type', )
    input_page = request.GET.get('page', )
    category = request.GET.get('category')
    keyword = request.GET.get('keyword')

    contents_per_page = 10

    if input_page == None:
        input_page = 1

    if keyword:
        if category == "":
            board = Board.objects.filter(
                Q(category=board_type) & Q(title__icontains=keyword) | Q(writer__profile__user__username=keyword) | Q(content__icontains=keyword)).distinct()
        elif category == "title":
            board = Board.objects.filter(
                Q(category=board_type) & Q(title__icontains=keyword)).distinct()
        elif category == "writer":
            board = Board.objects.filter(
                Q(category=board_type) & Q(writer__profile__user__username=keyword)).distinct()
        elif category == "content":
            board = Board.objects.filter(
                Q(category=board_type) & Q(content__icontains=keyword)).distinct()
    else:
        board = Board.objects.filter(category=board_type)

    paginator = Paginator(board, contents_per_page)
    this_page = paginator.page(input_page)
    # boards = this_page.object_list

    object = {}
    board_list = []
    for li in list(this_page):
        temp = {}
        temp['id'] = li.id
        temp['title'] = li.title
        temp['content'] = li.content
        temp['count'] = li.count
        temp['recommend'] = li.recommend
        temp['writer'] = str(li.writer)
        temp['create_date'] = str(li.create_date)[0:10]
        temp['modify_date'] = str(li.modify_date)[0:10]
        temp['category'] = li.category
        temp['get_absolute_url'] = li.get_absolute_url()
        board_list.append(temp)

    object['object'] = board_list
    object['current_page'] = input_page
    object['max_page'] = contents_per_page
    object['num_pages'] = paginator.num_pages
    object['has_prev'] = this_page.has_previous()
    object['has_next'] = this_page.has_next()
    object['start_index'] = this_page.start_index()

    if object['has_prev']:
        object['prev_page'] = this_page.previous_page_number()
    if object['has_next']:
        object['next_page'] = this_page.next_page_number()

    json_format = json.dumps(object)

    return HttpResponse(json_format, content_type="application/json:charset=UTF-8")

def write_comment(request):
    board_id = request.GET.get('board_id', )
    input_comment = request.GET.get('comment', )
    print(input_comment)
    user = request.user.pk

    comment = Comment()

    comment.board_id = Board(board_id)
    comment.writer = User(user)
    comment.content = input_comment
    comment.status = 'y'

    try:
        comment.save()

        result = json.dumps([
            {'result': 'seccess'}
        ])

    except Exception as e:
        print(e)
        result = json.dumps([
            {'result':'fail'}
        ])

    return HttpResponse(result, content_type="application/json:charset=UTF-8")

def add_like(request):
    board_id = request.GET.get('board_id', )
    user_type = request.user.profile.type
    liker = request.user.pk

    board = get_object_or_404(Board, pk=board_id)
    like = BoardLiker()

    if_liked = BoardLiker.objects.filter(liker=liker, board=board_id)

    if user_type != 1 and user_type != 2:
        result = json.dumps([
            {'likes': 'notLogin'}
        ])
        return HttpResponse(result, content_type="application/json:charset=UTF-8")
    elif if_liked:
        result = json.dumps([
            {'likes': 'already'}
        ])
        return HttpResponse(result, content_type="application/json:charset=UTF-8")
    else:
        like.liker = User(liker)
        like.board = board
        like.save()

        added = board.recommend + 1
        board.recommend = added
        board.save()
        result = json.dumps([
            {'likes' : added }
        ])
        return HttpResponse(result, content_type="application/json:charset=UTF-8")

def board_search(request):
    userid = request.GET.get('userid', )
    board = Board.objects.filter(Q(writer_id=userid) & Q(status='Y')).order_by('-id')
    this_page_num = request.GET.get('this_page',1)
    board_list = []
    page_size = 5
    p = Paginator(board, page_size)
    # for li in list(board):
    for li in p.page(this_page_num):
        temp = {}
        temp['id'] = li.id
        if len(li.title) > 30 : temp['title'] = str(li.title)[0:30]+"..."
        else : temp['title'] = li.title
        temp['content'] = li.content
        temp['recommend'] = li.recommend
        temp['create_date'] = str(li.create_date)[0:10]
        temp['category'] = li.category
        temp['count'] = li.count
        board_list.append(temp)

    start_seq = p.count - (page_size * (int(this_page_num) - 1))
    res = {
        'start_seq' : start_seq,
        'board_list': board_list,
        'current_page_num' : this_page_num,
        'max_page_num' : p.num_pages
    }
    json_format = json.dumps(res)
    return HttpResponse(json_format, content_type="application/json:charset=UTF-8")

RC/rccoin/wallet/board/templates/board/board_detail.html
{% extends 'base.html' %}
{% load staticfiles %}
<script src='{% static "jquery/jquery.min.js" %}'></script>
<link href="{% static 'bootstrap-4.2.1-dist/css/bootstrap.min.css' %}" rel="stylesheet">
<link href="{% static 'css/myinfo.css' %}" rel="stylesheet">
<link href="{% static 'css/modal.css' %}" rel="stylesheet">
<link href="https://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.9/summernote.css" rel="stylesheet">
{% block body %}

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.js"></script> 
<script src="https://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.9/summernote.js"></script>
<script src="{% static 'js/board.js' %}"></script>

<style>
    .btn{
        border: 1px solid rgb(113, 197, 93);
        border-radius: 7px;
        color: #fff;
        background-color: rgb(113, 197, 93);
        font-size: 11px;
        font-weight: 800;
        padding: 6px 21px;
        margin: 22px;
    }
    .page-item.active .page-link{
        background-color: rgb(113, 197, 93) !important;
        border-color: rgb(113, 197, 93) !important;
    }
    /*    --------------------------------------------------
	:: General
	-------------------------------------------------- */
    .submitbox{
    margin-top: 10%;
    border-top: 6px solid #7ac55d;
    background-color:#fff;
    /* padding: 20px; */
    padding-top: 20px;
    padding-bottom: 30px;
    padding-left: 20px;
    padding-right: 20px;
    box-shadow: 0 10px 10px -2px rgba(0,0,0,0.12),0 -2px 10px -2px rgba(0,0,0,0.12);    
    }
    .boxtitle {
        font-size: 28px;
        color: #7ac55d;
        font-weight: 500;
        letter-spacing: 1px;
    }
    .nav-tabs .nav-link {
        border: 1px soild #dee2e6;
        border-top-left-radius: 0.25rem;
        border-top-right-radius: 0.25rem;
        border-left: 1px solid #dee2e6;
        border-right: 1px solid #dee2e6;
        border-top: 1px solid #dee2e6;
        border-bottom: 1px solid #dee2e6;
    }

    @media (max-width: 700px) {
        thead {
            visibility: hidden;
        }
    } 
    .tag_text, thead {
        padding: 5px;
        text-align: center;
        white-space: nowrap;
    }
</style>


    <!-- Title -->
    <div id="contents" class="page-header">
        <div class="container">
            <div class="row page-title">
                <a>커뮤니티</a>
            </div>
        </div>
    </div>
    
    <div id="contents">
        <div class="container">
            <div class="row justify-content-center page">
                <div class="col-md card">
                    <div class="card-body">
                        <h5 class="card-subtitle"><a style="color:#00c746;">|</a> 게시판 글</h5>
                    </div>
                </div>
            </div>

            <div class="row justify-content-center page">
                <div class="col-md card">
                    <div class="card-body">
                    
                        <input type="text" id="from" value="{{ user.username }}" hidden />
                        <input type="text" id="u_id" value="{{ user.id }}" hidden />
            
                        <div style="margin-left:1px">
                            <ul class="nav nav-tabs" id="myTab" role="tablist">
                                <li class="row nav-item" style="margin-left: 1px; margin-right: 1px; margin-bottom: 10px; width: 100%">
                                    <a id="btn_board_type_1" class="nav-link btn_board_type_1"  style="min-width: 75px" onclick="back_to_list(1)"  href="{% url 'board:list' %}">가맹 게시판</a>
                                    <input type="hidden" id="board_type_1" value="1">&nbsp;
                                    <a id="btn_board_type_2" class="nav-link btn_board_type_2"  style="min-width: 75px" onclick="back_to_list(2)"  href="{% url 'board:list' %}">회원 게시판</a>
                                    <input type="hidden" id="board_type_2" value="2">
                                </li>
                            </ul>
                        </div>
                        <div class="content board_content" style="">
                            <div class="row" style="margin-left:3px;">
                                <h1 class="mt-4">{{ object.title }}</h1>
                            </div>
                            <br>
                            <tr>
                                <text class="date" style="display: inline-block; margin-left:5px;">
                                    <th style="border-right:1px solid #dee2e6">
                                        {{object.writer}}
                                    </th>&nbsp;&nbsp;&nbsp;
                                    <th>
                                        {{ object.modify_date|date:"Y F d" }}일
                                    </th>&nbsp;&nbsp;&nbsp;
                                    <th class="like" style="margin-right:50px;">
                                        <a><img src="{% static 'img/people.png' %}"></a>
                                        <span>{{ object.count }}</span>
                                        &nbsp;&nbsp;&nbsp;
                                        <a href="#" onclick="add_like({{ object.id }})"><img src="{% static 'img/heart.png' %}"></a>
                                        <span class="recommed_cnt">{{ object.recommend }}</span>
                                    </th>
                                </text>
                
                                <hr>
                                </br>
                                <div class="body" id="summernote">
                                    {{ object.content|safe }}
                                </div>
                            </tr>
                            <div>
                                {% if user.pk == object.writer.profile.pk %}
                                <a class="btn  btn_modify" href="{% url 'board:edit' object.id %}">수정</a>
                                <a class="btn btn_delete" href="{% url 'board:delete' object.id %}">삭제</a>
                                {% endif %}
                                <a class="btn" href="{% url 'board:list' %}">돌아가기</a>
                                <a class="btn btn_comment" onclick="comment.spread_comment({{ object.id }})">댓글 보기</a>
                            </div>
                            <div>
                                <a><img src="{% static 'img/comment.png' %}"></a>
                                <span>{{ comment_cnt }}</span>
                            </div>
                            <input class="input_comment" type='text' value='' style='width: 80%'>
                            <button class='btn btn-primary btn_comment_write' onclick="comment.write_comment({{ object.id }})">등록</button>
                            <div class="comment_area" id="comment_area" style="display: table; width: 100%;">
                                <ul class="comment_list" style="list-style:none; overflow: auto; max-height: 300px;"></ul>
                            </div>
                        </div>    
                    </div>
                </div>
            </div>
   
        </div>
    </div>
    

<script src="{% static 'jquery/jquery.min.js' %}"></script>
<script src="{% static 'bootstrap-4.2.1-dist/js/bootstrap.min.js' %}"></script>











{% comment %} -------------------------------------------------------- {% endcomment %}


<input type="hidden" id="user_type" name="user_type" value="{{ user.profile.type }}">
<input type="hidden" id="board_type" name="board_type" value="">


<input id="hdn_board_val" type="hidden" value="{{ object.id }}" >
<script type="text/javascript">
document.addEventListener("DOMContentLoaded", function(){


    var getCookie = function(name) {
      var value = document.cookie.match('(^|;) ?' + name + '=([^;]*)(;|$)');
      return value? value[2] : null;
    };

    var board_type = getCookie('current_board')

    ctl_btn_by_board_type(board_type)
    btn_click_ctl()

});

var comment = {};
comment.add_to_database = function(board_id){
    var input_comment = $('.input_comment').val();
    $('.input_comment').val("");
    if( input_comment != '' ){
        $.ajax({
            type: 'GET',
            url: '{% url 'board:write_comment' %}',
            data: {
                board_id : board_id,
                comment : input_comment
            },
            dataType : 'json',
            success: function(data) {
            },
            error: function( jqXHR, textStatus, errorThrown ){
                    alert('status: ' + textStatus + '\nerror: ' + jqXHR.error )
            }
        });
    }else{
        alert("댓글을 작성세요")
    }
};
comment.get_comment = function(board_id, do_spread){
    $.ajax({
        type: 'GET',
        url: '{% url 'board:comment' %}',
        data: {
            board_id : board_id
        },
        dataType : 'json',
        success: function(data) {
            comment.spread_data(data);
        },
        error: function( jqXHR, textStatus, errorThrown ){
                alert('status: ' + textStatus + '\nerror: ' + jqXHR.error )
        }
    });
};
comment.spread_comment = function(num){
    var board_id = num;
    $( ".comment_list" ).empty();
    if( $('.comment_area').hasClass('on') ){
        $('.comment_area').removeClass('on')
        $('.comment_area').css('display', 'none');
    }else{
        comment.get_comment(board_id);
        $('.comment_area').css('display', 'table');
        $('.comment_area').addClass('on');
    }
};
comment.spread_data = function(data){
    html_str = ""
    var result_data = []
    result_data = data
    $( ".comment_list" ).empty();
    if ( data != '' ){
        result_data.forEach(function(data){
            html_str += "<li>" + data.writer + "&nbsp; | &nbsp;" + data.time_diff + "</li>"
            html_str += "<li>" + data.content + "</li>"
        });
        $(".comment_area ul").append(html_str)
    }
};
comment.write_comment = function(board_id){
    
    comment.add_to_database(board_id);
    if($('.comment_area').hasClass('on')){
        comment.get_comment(board_id);
    }else{
        $('.comment_area').css('display', 'table');
        comment.get_comment(board_id);
        $('.comment_area').addClass('on');
    }
};

function add_like(board_id){
    $.ajax({
        type: 'GET',
        url: '{% url 'board:add_like' %}',
        data: {
            board_id : board_id
        },
        dataType : 'json',
        success: function(data) {
            if(data[0].likes == 'notLogin'){
                alert("로그인을 하셔야합니다.")
            }else if(data[0].likes == 'already'){
                alert("이미 좋아요를 누르셨습니다.")
            }else{
                $('.recommed_cnt').text(data[0].likes)
            }
        },
        error: function( jqXHR, textStatus, errorThrown ){
            alert("로그인을 하셔야합니다.")
        }
    });
}
$('#summernote').summernote();
$('.note-editable').attr('contenteditable', 'false');
</script>













{% endblock body %}

RC/rccoin/wallet/board/templates/board/board_edit.1.html
{% extends 'base.html' %}
{% load staticfiles %}

<link href='{% static "bootstrap-4.2.1-dist/css/bootstrap.css" %}' rel="stylesheet">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
{% block js %}
<script type="text/javascript" src="{% static '/js/board.js' %}"></script>
{% endblock %}
{% block body %}
<style>
    .btn{
        border: 1px solid rgb(113, 197, 93);
        border-radius: 7px;
        color: #fff;
        background-color: rgb(113, 197, 93);
        font-size: 11px;
        font-weight: 800;
        padding: 6px 21px;
        margin: 22px;
    }
    .page-item.active .page-link{
        background-color: rgb(113, 197, 93) !important;
        border-color: rgb(113, 197, 93) !important;
    }
    /*    --------------------------------------------------
	:: General
	-------------------------------------------------- */
    .submitbox{
    margin-top: 10%;
    border-top: 6px solid #7ac55d;
    background-color:#fff;
    /* padding: 20px; */
    padding-top: 20px;
    padding-bottom: 30px;
    padding-left: 20px;
    padding-right: 20px;
    box-shadow: 0 10px 10px -2px rgba(0,0,0,0.12),0 -2px 10px -2px rgba(0,0,0,0.12);    
    }
    .boxtitle {
        font-size: 28px;
        color: #7ac55d;
        font-weight: 500;
        letter-spacing: 1px;
    }
    .nav-tabs .nav-link {
        border: 1px soild #dee2e6;
        border-top-left-radius: 0.25rem;
        border-top-right-radius: 0.25rem;
        border-left: 1px solid #dee2e6;
        border-right: 1px solid #dee2e6;
        border-top: 1px solid #dee2e6;
        border-bottom: 1px solid #dee2e6;
    }

    @media (max-width: 700px) {
        thead {
            visibility: hidden;
        }
    } 
    .tag_text, thead {
        padding: 5px;
        text-align: center;
        white-space: nowrap;
    }

    .board_content{
        witdh: 80%
    }
    .content{
        {% comment %} height: 1000px; {% endcomment %}
    }
    #id_title{
        overflow: visible;
        margin-left: 120px;
        border: aqua;
    }
    #id_content{
        overflow: hidden;
        margin-left: 86px;
        border: aqua;
        height: 500px;
        width: 700px;
    }
    .btn_group{
        margin-top: 50px;
        margin-left: -342px;
    }
    .btn{
        border: 1px solid rgb(113, 197, 93);
        border-radius: 7px;
        color: #fff;
        background-color: rgb(113, 197, 93);
        font-size: 11px;
        font-weight: 800;
        padding: 6px 21px;
        margin: 5px;
    }
    .row {
        margin-left: -325px !important;
        margin-top: auto
    }
    .note-editor.note-frame .note-editing-area .note-editable{
        height: 500px;
    }
    .note-toolbar panel-heading{
        position: absolute !important;
    }
</style>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.js"></script>
  <script src="https://netdna.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.9/summernote.js"></script>
  <link href="https://netdna.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.css" rel="stylesheet">
  <link href="https://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.9/summernote.css" rel="stylesheet">


<section id="content">
	<input type="text" id="from" value="{{ user.username }}" hidden />
	<input type="text" id="u_id" value="{{ user.id }}" hidden />
 
	<div class="container">
        <div class="submitbox">
            <div class="content board_content" style="">
                {% if board.id %}
                    <form action="{% url 'board:edit' board_id=board.id %}" method="POST">
                {% else %}
                    <form action="{% url 'board:add' %}" method="POST">
                {% endif %}
                {% csrf_token %}
                    <fieldset class="aligned">
                        {{form.title.label_tag}} {{form.title}}
                        <hr>
                        {{ form.content|safe }}
                    </fieldset>
                        <div class="form-group row btn_group">
                            <div class="offset-md-3 col-md-9">
                                <input type="submit" class="btn" value="제출">
                                {% if board.id %}
                                <a class="btn" href="{{ board.get_absolute_url }}">돌아가기</a>
                                {% else %}
                                <a class="btn" href="{% url 'board:list' %}">돌아가기</a>
                                {% endif %}
                            </div>
                        </div>
                    </form>
                </div>    
        </div>
    </div>
    
</section>
<br>

<script type="text/javascript">
$('textarea').attr('id', 'summernote');
$('#summernote').summernote();
document.addEventListener("DOMContentLoaded", function(){
    var getCookie = function(name) {
      var value = document.cookie.match('(^|;) ?' + name + '=([^;]*)(;|$)');
      return value? value[2] : null;
    };

    var current_board = getCookie('current_board')

    ctl_btn_by_board_type(current_board)
    btn_click_ctl()

    $('#board_id').val(current_board)

});
</script>
{% endblock body %}